(()=>{
'use strict';
const WORKER='https://arm-pagos.alejandro-c23.workers.dev';
const SB_URL='https://odgpqgfkvrnexzsqrzus.supabase.co';
const SB_KEY='sb_publishable_UsxgoRc17ybij9rgOfDAPw_6Uz4N5dr';
const TRIAL_MS=5*60*1000, TRIAL_KEY='arm_hvac_trial_started_v1';
let mode='trial', isPro=true, sb=null, companyToken='';
const css=`<style id="armAccessCss">.arm-access-badge{position:fixed;z-index:2147483000;right:12px;top:12px;padding:7px 11px;border-radius:999px;background:#062238;color:#fff;border:1px solid #2b6b86;font:700 12px system-ui;box-shadow:0 5px 18px #0005}.arm-access-gate{position:fixed;z-index:2147483646;inset:0;background:rgba(2,10,18,.93);display:grid;place-items:center;padding:18px;font-family:system-ui}.arm-access-card{width:min(520px,100%);background:#0b1c29;color:#eef7fb;border:1px solid #31536a;border-radius:18px;padding:24px;box-shadow:0 25px 80px #000b}.arm-access-card h2{margin:0 0 8px}.arm-access-card p{color:#b8cad6;line-height:1.45}.arm-access-card input{box-sizing:border-box;width:100%;margin:6px 0;padding:12px;border-radius:10px;border:1px solid #41637a;background:#07141e;color:#fff}.arm-access-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.arm-access-actions button{padding:11px 14px;border:0;border-radius:10px;font-weight:800;cursor:pointer}.arm-access-actions .primary{background:#19a6a0;color:#fff}.arm-access-msg{min-height:20px;color:#ffd166!important;font-size:13px}.arm-pro-lock{opacity:.55!important}</style>`;
document.head.insertAdjacentHTML('beforeend',css);
function badge(){let b=document.querySelector('.arm-access-badge');if(!b){b=document.createElement('div');b.className='arm-access-badge';document.body.appendChild(b)}b.textContent=mode==='company'?'EMPRESA · PRO':mode==='pro'?'PRO':mode==='free'?'FREE':'PRUEBA · '+Math.max(0,Math.ceil((TRIAL_MS-(Date.now()-trialStart()))/60000))+' min';}
function trialStart(){let n=Number(localStorage.getItem(TRIAL_KEY));if(!n){n=Date.now();localStorage.setItem(TRIAL_KEY,String(n))}return n}
function gate(){if(document.querySelector('.arm-access-gate'))return;const d=document.createElement('div');d.className='arm-access-gate';d.innerHTML=`<div class="arm-access-card"><h2>Continúa con tu cuenta ARM</h2><p>La prueba de 5 minutos ha finalizado. Tu proyecto permanece abierto. Inicia sesión o crea una cuenta gratuita para continuar.</p><input data-a-email type="email" placeholder="Correo electrónico"><input data-a-pass type="password" placeholder="Contraseña (mín. 6 caracteres)"><div class="arm-access-actions"><button class="primary" data-a-login>Iniciar sesión</button><button data-a-register>Crear cuenta FREE</button></div><p class="arm-access-msg" data-a-msg></p><p>FREE mantiene diseño, cálculo, importación de imagen/DXF y PDF. PRO añade DXF, Word/Docs y Excel.</p></div>`;document.body.appendChild(d);const msg=d.querySelector('[data-a-msg]');const vals=()=>[d.querySelector('[data-a-email]').value.trim(),d.querySelector('[data-a-pass]').value];d.querySelector('[data-a-login]').onclick=async()=>{const [email,password]=vals();msg.textContent='Comprobando…';const {data,error}=await sb.auth.signInWithPassword({email,password});if(error){msg.textContent=error.message;return}await applyIndividual(data.session);d.remove()};d.querySelector('[data-a-register]').onclick=async()=>{const [email,password]=vals();if(password.length<6){msg.textContent='La contraseña debe tener al menos 6 caracteres.';return}msg.textContent='Creando cuenta…';const {data,error}=await sb.auth.signUp({email,password});if(error){msg.textContent=error.message;return}if(!data.session){msg.textContent='Cuenta creada. Revisa tu correo para confirmar el registro y después inicia sesión.';return}await applyIndividual(data.session);d.remove()};}
async function applyIndividual(session){mode='free';isPro=false;if(session){try{const {data,error}=await sb.rpc('my_application_license',{p_slug:'arm-hvac-ducts'});if(!error){const x=Array.isArray(data)?data[0]:data;if(x?.is_pro){mode='pro';isPro=true}}}catch(_){}}badge();}
async function companyBeat(){if(!companyToken)return false;try{const r=await fetch(WORKER+'/company/heartbeat',{method:'POST',headers:{Authorization:'Bearer '+companyToken}});if(!r.ok)throw 0;mode='company';isPro=true;badge();return true}catch(_){companyToken='';sessionStorage.removeItem('arm_hvac_company_token');return false}}
function lockNotice(){alert('Esta exportación pertenece a ARM HVAC DUCTS PRO.\n\nFREE incluye diseño, cálculo, importación DXF/imagen y exportación PDF.\nPRO añade exportación DXF, Word/Docs y Excel.');}
function protect(){document.addEventListener('click',e=>{if(isPro)return;const b=e.target.closest('button');if(!b)return;const t=(b.textContent||'').trim().toLowerCase();if(b.id==='btnExportDxf'||b.matches('[data-docx],[data-xlsx]')||t.includes('exportar dxf')||t==='word / docs'||t==='xlsx'){e.preventDefault();e.stopImmediatePropagation();lockNotice()}},true);const patch=()=>{if(window.ARM_HVAC_DUCT?.showDxfExportDialog&&!window.ARM_HVAC_DUCT.__accessPatched){const orig=window.ARM_HVAC_DUCT.showDxfExportDialog;window.ARM_HVAC_DUCT.showDxfExportDialog=()=>isPro?orig():lockNotice();window.ARM_HVAC_DUCT.__accessPatched=true}if(window.ARM_DXF?.exportDXF&&!window.ARM_DXF.__accessPatched){const orig=window.ARM_DXF.exportDXF;window.ARM_DXF.exportDXF=(...a)=>isPro?orig(...a):lockNotice();window.ARM_DXF.__accessPatched=true}};patch();setInterval(patch,1000)}
async function init(){const hash=new URLSearchParams(location.hash.slice(1));const ht=hash.get('company_token');if(ht){sessionStorage.setItem('arm_hvac_company_token',ht);history.replaceState(null,'',location.pathname+location.search)}companyToken=sessionStorage.getItem('arm_hvac_company_token')||'';if(companyToken&&await companyBeat()){setInterval(companyBeat,180000);protect();return}if(!window.supabase){console.error('Supabase JS no disponible');return}sb=window.supabase.createClient(SB_URL,SB_KEY);const {data}=await sb.auth.getSession();if(data?.session){await applyIndividual(data.session);protect();return}const elapsed=Date.now()-trialStart();mode='trial';isPro=true;badge();protect();if(elapsed>=TRIAL_MS)gate();else setTimeout(gate,TRIAL_MS-elapsed);setInterval(badge,30000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
